/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intefacegraficadelegacia;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.*;

/**
 *
 * @author julia
 */
public class IGCadastrarSuspeito extends javax.swing.JFrame {

    /**
     * Creates new form IGCadastrarSuspeito
     */
    public IGCadastrarSuspeito() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoBranco = new javax.swing.JPanel();
        textoEndereco = new javax.swing.JLabel();
        inputEndereco = new javax.swing.JTextField();
        textoNome = new javax.swing.JLabel();
        textoDescricao = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputDescricao = new javax.swing.JTextField();
        textoNasc = new javax.swing.JLabel();
        VoltarBtn = new javax.swing.JButton();
        inputNasc = new javax.swing.JTextField();
        logoDel = new javax.swing.JLabel();
        textoDel = new javax.swing.JLabel();
        cadSusBtn = new javax.swing.JButton();
        linhaCc2 = new javax.swing.JPanel();
        linhaAe2 = new javax.swing.JPanel();
        textoCadSus = new javax.swing.JLabel();
        btnInicioLinha = new javax.swing.JButton();
        btnDelLinha = new javax.swing.JButton();
        btnServicosLinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundoBranco.setBackground(new java.awt.Color(255, 255, 255));

        textoEndereco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoEndereco.setForeground(new java.awt.Color(66, 80, 81));
        textoEndereco.setText("ENDERÇO:");

        inputEndereco.setForeground(new java.awt.Color(66, 80, 81));
        inputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnderecoActionPerformed(evt);
            }
        });

        textoNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoNome.setForeground(new java.awt.Color(66, 80, 81));
        textoNome.setText("NOME:");

        textoDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoDescricao.setForeground(new java.awt.Color(66, 80, 81));
        textoDescricao.setText("DESCRIÇÃO:");

        inputNome.setForeground(new java.awt.Color(66, 80, 81));
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        inputDescricao.setForeground(new java.awt.Color(66, 80, 81));

        textoNasc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoNasc.setForeground(new java.awt.Color(66, 80, 81));
        textoNasc.setText("DATA DE NASCIMENTO:");

        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setOpaque(true);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        inputNasc.setForeground(new java.awt.Color(66, 80, 81));

        logoDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N

        textoDel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoDel.setForeground(new java.awt.Color(66, 80, 81));
        textoDel.setText("DELEGACIA");

        cadSusBtn.setBackground(new java.awt.Color(242, 242, 242));
        cadSusBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadSusBtn.setForeground(new java.awt.Color(66, 80, 81));
        cadSusBtn.setText("CADASTRAR SUSPEITO");
        cadSusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSusBtnActionPerformed(evt);
            }
        });

        linhaAe2.setBackground(new java.awt.Color(66, 80, 81));
        linhaAe2.setForeground(new java.awt.Color(66, 80, 81));

        javax.swing.GroupLayout linhaAe2Layout = new javax.swing.GroupLayout(linhaAe2);
        linhaAe2.setLayout(linhaAe2Layout);
        linhaAe2Layout.setHorizontalGroup(
            linhaAe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaAe2Layout.setVerticalGroup(
            linhaAe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        textoCadSus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCadSus.setForeground(new java.awt.Color(66, 80, 81));
        textoCadSus.setText("CADASTRAR SUSPEITO");

        btnInicioLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnInicioLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnInicioLinha.setText("Início");
        btnInicioLinha.setBorder(null);
        btnInicioLinha.setBorderPainted(false);
        btnInicioLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLinhaActionPerformed(evt);
            }
        });

        btnDelLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnDelLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnDelLinha.setText("Delegacia");
        btnDelLinha.setBorder(null);
        btnDelLinha.setBorderPainted(false);
        btnDelLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLinhaActionPerformed(evt);
            }
        });

        btnServicosLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnServicosLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnServicosLinha.setText("Serviços");
        btnServicosLinha.setBorder(null);
        btnServicosLinha.setBorderPainted(false);
        btnServicosLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linhaCc2Layout = new javax.swing.GroupLayout(linhaCc2);
        linhaCc2.setLayout(linhaCc2Layout);
        linhaCc2Layout.setHorizontalGroup(
            linhaCc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaAe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(linhaCc2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(textoCadSus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        linhaCc2Layout.setVerticalGroup(
            linhaCc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linhaCc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linhaAe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linhaCc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCadSus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fundoBrancoLayout = new javax.swing.GroupLayout(fundoBranco);
        fundoBranco.setLayout(fundoBrancoLayout);
        fundoBrancoLayout.setHorizontalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaCc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoBrancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoBrancoLayout.createSequentialGroup()
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(VoltarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(logoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoDel))
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(345, 345, 345)
                                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoNome)
                                    .addComponent(textoNasc)
                                    .addComponent(inputNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoEndereco)
                                    .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoDescricao)
                                    .addComponent(inputDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoBrancoLayout.createSequentialGroup()
                        .addComponent(cadSusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))))
        );
        fundoBrancoLayout.setVerticalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(textoDel))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(logoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linhaCc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(textoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoNasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(textoDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cadSusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        servicosPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void cadSusBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (inputNome.getText().isEmpty() || inputNasc.getText().isEmpty() || inputEndereco.getText().isEmpty() ||
                inputDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite todos os dados!");
        } else {
            JOptionPane.showMessageDialog(null, "Dados Cadastrados!");
            Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            servicosPage.setVisible(true);
            this.dispose();
        }
    }

    
    private void btnInicioLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLinhaActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        inicioPage.setVisible(true);
        this.dispose();
        btnInicioLinha.setVisible(false);
    }//GEN-LAST:event_btnInicioLinhaActionPerformed

    private void btnDelLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLinhaActionPerformed
        IGDelegacia delegaciaPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        delegaciaPage.setVisible(true);
        this.dispose();
        btnDelLinha.setVisible(false); 
    }//GEN-LAST:event_btnDelLinhaActionPerformed

    private void btnServicosLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosLinhaActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        servicosPage.setVisible(true);
        this.dispose();
        btnServicosLinha.setVisible(false);
    }//GEN-LAST:event_btnServicosLinhaActionPerformed

    private void inputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarSuspeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarSuspeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarSuspeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarSuspeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGCadastrarSuspeito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JButton btnDelLinha;
    private javax.swing.JButton btnInicioLinha;
    private javax.swing.JButton btnServicosLinha;
    private javax.swing.JButton cadSusBtn;
    private javax.swing.JPanel fundoBranco;
    private javax.swing.JTextField inputDescricao;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JTextField inputNasc;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPanel linhaAe2;
    private javax.swing.JPanel linhaCc2;
    private javax.swing.JLabel logoDel;
    private javax.swing.JLabel textoCadSus;
    private javax.swing.JLabel textoDel;
    private javax.swing.JLabel textoDescricao;
    private javax.swing.JLabel textoEndereco;
    private javax.swing.JLabel textoNasc;
    private javax.swing.JLabel textoNome;
    // End of variables declaration//GEN-END:variables
}
