/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intefacegraficadelegacia;

import classes.Policial;
import entity.Case;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class IGCadastrarPolicial extends javax.swing.JFrame {

    /**
     * Creates new form IGCadastrarPolicial
     */
    public IGCadastrarPolicial() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeDepartamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enderecoDepartamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contatoDepartamento = new javax.swing.JTextField();
        botaoCadastroDept = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nomeDepartamento1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        enderecoDepartamento1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        contatoDepartamento1 = new javax.swing.JTextField();
        botaoCadastroDept1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        fundoBranco = new javax.swing.JPanel();
        logoDel = new javax.swing.JLabel();
        textoDel = new javax.swing.JLabel();
        linhaCc = new javax.swing.JPanel();
        linhaAe = new javax.swing.JPanel();
        textoCadPol = new javax.swing.JLabel();
        btnInicioLinha = new javax.swing.JButton();
        btnDelLinha = new javax.swing.JButton();
        btnServicosLinha = new javax.swing.JButton();
        textoNome = new javax.swing.JLabel();
        inputNomePol = new javax.swing.JTextField();
        textoAge = new javax.swing.JLabel();
        inputNasc = new javax.swing.JTextField();
        textoSal = new javax.swing.JLabel();
        inputSal = new javax.swing.JTextField();
        cadPolBtn = new javax.swing.JButton();
        textoCargo = new javax.swing.JLabel();
        inputCargo = new javax.swing.JTextField();
        textoDtContrat = new javax.swing.JLabel();
        inputDtContrat = new javax.swing.JTextField();
        VoltarBtn = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 80, 81));
        jLabel7.setText("DEPARTAMENTOS CADASTRADOS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 80, 81));
        jLabel4.setText("NOME DO DEPARTAMENTO:");

        nomeDepartamento.setForeground(new java.awt.Color(66, 80, 81));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 80, 81));
        jLabel5.setText("ENDEREÇO:");

        enderecoDepartamento.setForeground(new java.awt.Color(66, 80, 81));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 80, 81));
        jLabel6.setText("CONTATO:");

        contatoDepartamento.setForeground(new java.awt.Color(66, 80, 81));

        botaoCadastroDept.setBackground(new java.awt.Color(242, 242, 242));
        botaoCadastroDept.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCadastroDept.setForeground(new java.awt.Color(66, 80, 81));
        botaoCadastroDept.setText("CADASTRAR DEPARTAMENTO");

        jScrollPane1.setForeground(new java.awt.Color(66, 80, 81));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Departamento", "Endereço", "Contato"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 80, 81));
        jLabel8.setText("DEPARTAMENTOS CADASTRADOS");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 80, 81));
        jLabel9.setText("NOME DO DEPARTAMENTO:");

        nomeDepartamento1.setForeground(new java.awt.Color(66, 80, 81));
        nomeDepartamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDepartamento1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 80, 81));
        jLabel10.setText("ENDEREÇO:");

        enderecoDepartamento1.setForeground(new java.awt.Color(66, 80, 81));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 80, 81));
        jLabel11.setText("CONTATO:");

        contatoDepartamento1.setForeground(new java.awt.Color(66, 80, 81));

        botaoCadastroDept1.setBackground(new java.awt.Color(242, 242, 242));
        botaoCadastroDept1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCadastroDept1.setForeground(new java.awt.Color(66, 80, 81));
        botaoCadastroDept1.setText("CADASTRAR DEPARTAMENTO");
        botaoCadastroDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroDept1ActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(66, 80, 81));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Departamento", "Endereço", "Contato"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundoBranco.setBackground(new java.awt.Color(255, 255, 255));

        logoDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N

        textoDel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoDel.setForeground(new java.awt.Color(66, 80, 81));
        textoDel.setText("DELEGACIA");

        linhaAe.setBackground(new java.awt.Color(66, 80, 81));
        linhaAe.setForeground(new java.awt.Color(66, 80, 81));

        javax.swing.GroupLayout linhaAeLayout = new javax.swing.GroupLayout(linhaAe);
        linhaAe.setLayout(linhaAeLayout);
        linhaAeLayout.setHorizontalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaAeLayout.setVerticalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        textoCadPol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCadPol.setForeground(new java.awt.Color(66, 80, 81));
        textoCadPol.setText("CADASTRAR POLICIAL");

        btnInicioLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnInicioLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnInicioLinha.setText("Início");
        btnInicioLinha.setBorder(null);
        btnInicioLinha.setBorderPainted(false);
        btnInicioLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLinhaActionPerformed(evt);
            }
        });

        btnDelLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnDelLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnDelLinha.setText("Delegacia");
        btnDelLinha.setBorder(null);
        btnDelLinha.setBorderPainted(false);
        btnDelLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLinhaActionPerformed(evt);
            }
        });

        btnServicosLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnServicosLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnServicosLinha.setText("Serviços");
        btnServicosLinha.setBorder(null);
        btnServicosLinha.setBorderPainted(false);
        btnServicosLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linhaCcLayout = new javax.swing.GroupLayout(linhaCc);
        linhaCc.setLayout(linhaCcLayout);
        linhaCcLayout.setHorizontalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaAe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(textoCadPol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        linhaCcLayout.setVerticalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linhaAe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoCadPol)
                    .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoNome.setForeground(new java.awt.Color(66, 80, 81));
        textoNome.setText("NOME:");

        inputNomePol.setForeground(new java.awt.Color(66, 80, 81));
        inputNomePol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomePolActionPerformed(evt);
            }
        });

        textoAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoAge.setForeground(new java.awt.Color(66, 80, 81));
        textoAge.setText("DATA DE NASCIMENTO:");

        inputNasc.setForeground(new java.awt.Color(66, 80, 81));

        textoSal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoSal.setForeground(new java.awt.Color(66, 80, 81));
        textoSal.setText("SALÁRIO:");

        inputSal.setForeground(new java.awt.Color(66, 80, 81));

        cadPolBtn.setBackground(new java.awt.Color(242, 242, 242));
        cadPolBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadPolBtn.setForeground(new java.awt.Color(66, 80, 81));
        cadPolBtn.setText("CADASTRAR POLICIAL");
        cadPolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPolBtnActionPerformed(evt);
            }
        });

        textoCargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCargo.setForeground(new java.awt.Color(66, 80, 81));
        textoCargo.setText("CARGO:");

        inputCargo.setForeground(new java.awt.Color(66, 80, 81));

        textoDtContrat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoDtContrat.setForeground(new java.awt.Color(66, 80, 81));
        textoDtContrat.setText("DATA DE CONTRATAÇÃO:");

        inputDtContrat.setForeground(new java.awt.Color(66, 80, 81));

        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setOpaque(true);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoBrancoLayout = new javax.swing.GroupLayout(fundoBranco);
        fundoBranco.setLayout(fundoBrancoLayout);
        fundoBrancoLayout.setHorizontalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaCc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoBrancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cadPolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(VoltarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(logoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoDel))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNomePol, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoNome)
                            .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(fundoBrancoLayout.createSequentialGroup()
                                    .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(inputCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoAge)
                                            .addComponent(inputNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(65, 65, 65)
                                    .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoSal)
                                        .addComponent(inputSal, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(fundoBrancoLayout.createSequentialGroup()
                                    .addComponent(textoCargo)
                                    .addGap(280, 280, 280)
                                    .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoDtContrat)
                                        .addComponent(inputDtContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        fundoBrancoLayout.setVerticalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(textoDel))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(logoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linhaCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(textoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomePol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAge)
                    .addComponent(textoSal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCargo)
                    .addComponent(textoDtContrat))
                .addGap(3, 3, 3)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDtContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(cadPolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDepartamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDepartamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDepartamento1ActionPerformed

    private void botaoCadastroDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroDept1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroDept1ActionPerformed

    private void inputNomePolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomePolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomePolActionPerformed

    private void cadPolBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (inputNomePol.getText().isEmpty() || inputNasc.getText().isEmpty() || inputSal.getText().isEmpty() ||
                inputCargo.getText().isEmpty() || inputDtContrat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite todos os dados!");
        } else {
            JOptionPane.showMessageDialog(null, "Dados Cadastrados!");
            Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            servicosPage.setVisible(true);
            this.dispose();
        }
    }
    
    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            servicosPage.setVisible(true);
            this.dispose();
            VoltarBtn.setVisible(false);    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void btnInicioLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLinhaActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        inicioPage.setVisible(true);
        this.dispose();
        btnInicioLinha.setVisible(false);
    }//GEN-LAST:event_btnInicioLinhaActionPerformed

    private void btnDelLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLinhaActionPerformed
        IGDelegacia delegaciaPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        delegaciaPage.setVisible(true);
        this.dispose();
        btnDelLinha.setVisible(false); 
    }//GEN-LAST:event_btnDelLinhaActionPerformed

    private void btnServicosLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosLinhaActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        servicosPage.setVisible(true);
        this.dispose();
        btnServicosLinha.setVisible(false);
    }//GEN-LAST:event_btnServicosLinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarPolicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarPolicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarPolicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGCadastrarPolicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGCadastrarPolicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JButton botaoCadastroDept;
    private javax.swing.JButton botaoCadastroDept1;
    private javax.swing.JButton btnDelLinha;
    private javax.swing.JButton btnInicioLinha;
    private javax.swing.JButton btnServicosLinha;
    private javax.swing.JButton cadPolBtn;
    private javax.swing.JTextField contatoDepartamento;
    private javax.swing.JTextField contatoDepartamento1;
    private javax.swing.JTextField enderecoDepartamento;
    private javax.swing.JTextField enderecoDepartamento1;
    private javax.swing.JPanel fundoBranco;
    private javax.swing.JTextField inputCargo;
    private javax.swing.JTextField inputDtContrat;
    private javax.swing.JTextField inputNasc;
    private javax.swing.JTextField inputNomePol;
    private javax.swing.JTextField inputSal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel linhaAe;
    private javax.swing.JPanel linhaCc;
    private javax.swing.JLabel logoDel;
    private javax.swing.JTextField nomeDepartamento;
    private javax.swing.JTextField nomeDepartamento1;
    private javax.swing.JLabel textoAge;
    private javax.swing.JLabel textoCadPol;
    private javax.swing.JLabel textoCargo;
    private javax.swing.JLabel textoDel;
    private javax.swing.JLabel textoDtContrat;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoSal;
    // End of variables declaration//GEN-END:variables
}

