/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intefacegraficadelegacia;
import database.Database;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author julia
 */
public class IGDelegacia extends javax.swing.JFrame {

    /**
     * Creates new form IGDelegacia
     */
    public IGDelegacia() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        linhaCc = new javax.swing.JPanel();
        linhaAe = new javax.swing.JPanel();
        textoServicos = new javax.swing.JLabel();
        btnInicioLinha = new javax.swing.JButton();
        btnDelLinha = new javax.swing.JButton();
        btnServicosLinha = new javax.swing.JButton();
        textoDel = new javax.swing.JLabel();
        logoDel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCasosCadastrados = new javax.swing.JTable();
        jButtonImport = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        linhaAe.setBackground(new java.awt.Color(66, 80, 81));

        javax.swing.GroupLayout linhaAeLayout = new javax.swing.GroupLayout(linhaAe);
        linhaAe.setLayout(linhaAeLayout);
        linhaAeLayout.setHorizontalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaAeLayout.setVerticalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        textoServicos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoServicos.setForeground(new java.awt.Color(66, 80, 81));
        textoServicos.setText("DELEGACIA");

        btnInicioLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnInicioLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnInicioLinha.setText("Início");
        btnInicioLinha.setBorder(null);
        btnInicioLinha.setBorderPainted(false);
        btnInicioLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLinhaActionPerformed(evt);
            }
        });

        btnDelLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnDelLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnDelLinha.setText("Delegacia");
        btnDelLinha.setBorder(null);
        btnDelLinha.setBorderPainted(false);
        btnDelLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLinhaActionPerformed(evt);
            }
        });

        btnServicosLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnServicosLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnServicosLinha.setText("Serviços");
        btnServicosLinha.setBorder(null);
        btnServicosLinha.setBorderPainted(false);
        btnServicosLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linhaCcLayout = new javax.swing.GroupLayout(linhaCc);
        linhaCc.setLayout(linhaCcLayout);
        linhaCcLayout.setHorizontalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaAe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(textoServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 591, Short.MAX_VALUE)
                .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        linhaCcLayout.setVerticalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linhaAe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoServicos)
                    .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        textoDel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoDel.setForeground(new java.awt.Color(66, 80, 81));
        textoDel.setText("DELEGACIA");

        logoDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N

        tableCasosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCasosCadastrados);

        jButtonImport.setBackground(new java.awt.Color(66, 80, 81));
        jButtonImport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonImport.setForeground(new java.awt.Color(255, 255, 255));
        jButtonImport.setText("VER CASOS CADASTRADOS");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setOpaque(true);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaCc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(VoltarBtn)
                .addGap(18, 18, 18)
                .addComponent(logoDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1)
                .addGap(30, 30, 30)
                .addComponent(jButtonImport)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linhaCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(jButtonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLinhaActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        inicioPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioLinhaActionPerformed

    
    
    private void btnDelLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLinhaActionPerformed
        IGDelegacia delegaciaPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        delegaciaPage.setVisible(true);
        this.dispose();
        btnDelLinha.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelLinhaActionPerformed

    private void btnServicosLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosLinhaActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        servicosPage.setVisible(true);
        this.dispose();
        btnServicosLinha.setVisible(false);
    }//GEN-LAST:event_btnServicosLinhaActionPerformed


    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        String filePath = "C:\\Users\\julia\\Downloads\\2° período BSI\\Programação Orientada a Objetos\\code_v01\\src\\main\\java\\database\\cases_db.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)tableCasosCadastrados.getModel();
            model.setColumnIdentifiers(columnsName);
            Object[] tableLines = br.lines().toArray();

            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
        } catch (Exception ex) {
            Logger.getLogger(IGDelegacia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        inicioPage.setVisible(true);
        this.dispose();
        VoltarBtn.setVisible(false);
    }//GEN-LAST:event_VoltarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGDelegacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGDelegacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JButton btnDelLinha;
    private javax.swing.JButton btnInicioLinha;
    private javax.swing.JButton btnServicosLinha;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel linhaAe;
    private javax.swing.JPanel linhaCc;
    private javax.swing.JLabel logoDel;
    private javax.swing.JTable tableCasosCadastrados;
    private javax.swing.JLabel textoDel;
    private javax.swing.JLabel textoServicos;
    // End of variables declaration//GEN-END:variables
}
