/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intefacegraficadelegacia;

import javax.swing.JFrame;

/**
 *
 * @author julia
 */
public class IGInicio extends javax.swing.JFrame {

    /**
     * Creates new form IGInicio
     */
    public IGInicio() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoBranco = new javax.swing.JPanel();
        logoDel = new javax.swing.JLabel();
        textoDel = new javax.swing.JLabel();
        linhaCc = new javax.swing.JPanel();
        linhaAe = new javax.swing.JPanel();
        btnInicioLinha = new javax.swing.JButton();
        btnDelLinha = new javax.swing.JButton();
        btnServicosLinha = new javax.swing.JButton();
        textoInicio = new javax.swing.JLabel();
        textoLateral = new javax.swing.JLabel();
        imgDel = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        textoDescDel = new javax.swing.JLabel();
        imgServ = new javax.swing.JLabel();
        btnServicos = new javax.swing.JButton();
        textoDescServ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundoBranco.setBackground(new java.awt.Color(255, 255, 255));

        logoDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N

        textoDel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoDel.setForeground(new java.awt.Color(66, 80, 81));
        textoDel.setText("DELEGACIA");

        linhaAe.setBackground(new java.awt.Color(66, 80, 81));

        javax.swing.GroupLayout linhaAeLayout = new javax.swing.GroupLayout(linhaAe);
        linhaAe.setLayout(linhaAeLayout);
        linhaAeLayout.setHorizontalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaAeLayout.setVerticalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        btnInicioLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnInicioLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnInicioLinha.setText("Início");
        btnInicioLinha.setBorder(null);
        btnInicioLinha.setBorderPainted(false);
        btnInicioLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLinhaActionPerformed(evt);
            }
        });

        btnDelLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnDelLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnDelLinha.setText("Delegacia");
        btnDelLinha.setBorder(null);
        btnDelLinha.setBorderPainted(false);
        btnDelLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLinhaActionPerformed(evt);
            }
        });

        btnServicosLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnServicosLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnServicosLinha.setText("Serviços");
        btnServicosLinha.setBorder(null);
        btnServicosLinha.setBorderPainted(false);
        btnServicosLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosLinhaActionPerformed(evt);
            }
        });

        textoInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoInicio.setForeground(new java.awt.Color(66, 80, 81));
        textoInicio.setText("INÍCIO");

        javax.swing.GroupLayout linhaCcLayout = new javax.swing.GroupLayout(linhaCc);
        linhaCc.setLayout(linhaCcLayout);
        linhaCcLayout.setHorizontalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaAe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linhaCcLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(textoInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        linhaCcLayout.setVerticalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linhaAe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoInicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text.png"))); // NOI18N

        imgDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleg.png"))); // NOI18N

        btnDel.setBackground(new java.awt.Color(66, 80, 81));
        btnDel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("DELEGACIA");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        textoDescDel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        textoDescDel.setForeground(new java.awt.Color(66, 80, 81));
        textoDescDel.setText("Ver Casos Cadastrados.");

        imgServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bolet.png"))); // NOI18N

        btnServicos.setBackground(new java.awt.Color(66, 80, 81));
        btnServicos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnServicos.setText("SERVIÇOS");
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });

        textoDescServ.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        textoDescServ.setForeground(new java.awt.Color(66, 80, 81));
        textoDescServ.setText("Cadastrar Casos.");

        javax.swing.GroupLayout fundoBrancoLayout = new javax.swing.GroupLayout(fundoBranco);
        fundoBranco.setLayout(fundoBrancoLayout);
        fundoBrancoLayout.setHorizontalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(logoDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(textoLateral)
                .addGap(111, 111, 111)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgDel)
                    .addComponent(imgServ))
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(btnServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(textoDescServ))
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(textoDescDel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(linhaCc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fundoBrancoLayout.setVerticalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoDel))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(textoDel)))
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(imgDel)
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textoDescServ))
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(imgServ))))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linhaCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(textoLateral))
                            .addGroup(fundoBrancoLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoDescDel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLinhaActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        inicioPage.setVisible(true);
        this.dispose();
        btnInicioLinha.setVisible(false);    }//GEN-LAST:event_btnInicioLinhaActionPerformed

    private void btnDelLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLinhaActionPerformed
        IGDelegacia delegaciaPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        delegaciaPage.setVisible(true);
        this.dispose();
        btnDelLinha.setVisible(false); 
    }//GEN-LAST:event_btnDelLinhaActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            servicosPage.setVisible(true);
            this.dispose();
            btnServicos.setVisible(false);

    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnServicosLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosLinhaActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            servicosPage.setVisible(true);
            this.dispose();
            btnServicos.setVisible(false);    }//GEN-LAST:event_btnServicosLinhaActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
            IGDelegacia delegaciaPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            delegaciaPage.setVisible(true);
            this.dispose();
            btnDel.setVisible(false);    }//GEN-LAST:event_btnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDelLinha;
    private javax.swing.JButton btnInicioLinha;
    private javax.swing.JButton btnServicos;
    private javax.swing.JButton btnServicosLinha;
    private javax.swing.JPanel fundoBranco;
    private javax.swing.JLabel imgDel;
    private javax.swing.JLabel imgServ;
    private javax.swing.JPanel linhaAe;
    private javax.swing.JPanel linhaCc;
    private javax.swing.JLabel logoDel;
    private javax.swing.JLabel textoDel;
    private javax.swing.JLabel textoDescDel;
    private javax.swing.JLabel textoDescServ;
    private javax.swing.JLabel textoInicio;
    private javax.swing.JLabel textoLateral;
    // End of variables declaration//GEN-END:variables
}
