/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.intefacegraficadelegacia;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class Servicos extends javax.swing.JFrame {

    /**
     * Creates new form Servicos
     */
    public Servicos() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fundoBranco = new javax.swing.JPanel();
        logoDel = new javax.swing.JLabel();
        textoDel = new javax.swing.JLabel();
        linhaCc = new javax.swing.JPanel();
        linhaAe = new javax.swing.JPanel();
        textoServicos = new javax.swing.JLabel();
        btnInicioLinha = new javax.swing.JButton();
        btnDelLinha = new javax.swing.JButton();
        btnServicosLinha = new javax.swing.JButton();
        cadDeptBtn = new javax.swing.JButton();
        cadPolBtn = new javax.swing.JButton();
        cadDelBtn = new javax.swing.JButton();
        cadSuspBtn = new javax.swing.JButton();
        cadTestBtn = new javax.swing.JButton();
        cadCasoBtn = new javax.swing.JButton();
        savCasBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        fundoBranco.setBackground(new java.awt.Color(255, 255, 255));

        logoDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N

        textoDel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoDel.setForeground(new java.awt.Color(66, 80, 81));
        textoDel.setText("DELEGACIA");

        linhaAe.setBackground(new java.awt.Color(66, 80, 81));

        javax.swing.GroupLayout linhaAeLayout = new javax.swing.GroupLayout(linhaAe);
        linhaAe.setLayout(linhaAeLayout);
        linhaAeLayout.setHorizontalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaAeLayout.setVerticalGroup(
            linhaAeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        textoServicos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoServicos.setForeground(new java.awt.Color(66, 80, 81));
        textoServicos.setText("SERVIÇOS");

        btnInicioLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnInicioLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnInicioLinha.setText("Início");
        btnInicioLinha.setBorder(null);
        btnInicioLinha.setBorderPainted(false);
        btnInicioLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLinhaActionPerformed(evt);
            }
        });

        btnDelLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnDelLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnDelLinha.setText("Delegacia");
        btnDelLinha.setBorder(null);
        btnDelLinha.setBorderPainted(false);
        btnDelLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLinhaActionPerformed(evt);
            }
        });

        btnServicosLinha.setBackground(new java.awt.Color(242, 242, 242));
        btnServicosLinha.setForeground(new java.awt.Color(66, 80, 81));
        btnServicosLinha.setText("Serviços");
        btnServicosLinha.setBorder(null);
        btnServicosLinha.setBorderPainted(false);
        btnServicosLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linhaCcLayout = new javax.swing.GroupLayout(linhaCc);
        linhaCc.setLayout(linhaCcLayout);
        linhaCcLayout.setHorizontalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaAe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(textoServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        linhaCcLayout.setVerticalGroup(
            linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linhaCcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linhaAe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoServicos)
                    .addGroup(linhaCcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnServicosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInicioLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        cadDeptBtn.setBackground(new java.awt.Color(66, 80, 81));
        cadDeptBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadDeptBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadDeptBtn.setText("Cadastrar Departamento");
        cadDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDeptBtnActionPerformed(evt);
            }
        });

        cadPolBtn.setBackground(new java.awt.Color(66, 80, 81));
        cadPolBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadPolBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadPolBtn.setText("Cadastrar Policial");
        cadPolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPolBtnActionPerformed(evt);
            }
        });

        cadDelBtn.setBackground(new java.awt.Color(66, 80, 81));
        cadDelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadDelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadDelBtn.setText("Cadastrar Delegacia");
        cadDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDelBtnActionPerformed(evt);
            }
        });

        cadSuspBtn.setBackground(new java.awt.Color(66, 80, 81));
        cadSuspBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadSuspBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadSuspBtn.setText("Cadastrar Suspeito");
        cadSuspBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSuspBtnActionPerformed(evt);
            }
        });

        cadTestBtn.setBackground(new java.awt.Color(66, 80, 81));
        cadTestBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadTestBtn.setText("Cadastrar Testemunha");
        cadTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTestBtnActionPerformed(evt);
            }
        });

        cadCasoBtn.setBackground(new java.awt.Color(66, 80, 81));
        cadCasoBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadCasoBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadCasoBtn.setText("Cadastrar Caso");
        cadCasoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCasoBtnActionPerformed(evt);
            }
        });

        savCasBtn.setBackground(new java.awt.Color(66, 80, 81));
        savCasBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savCasBtn.setForeground(new java.awt.Color(255, 255, 255));
        savCasBtn.setText("Salvar Caso");
        savCasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savCasBtnActionPerformed(evt);
            }
        });

        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setOpaque(true);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoBrancoLayout = new javax.swing.GroupLayout(fundoBranco);
        fundoBranco.setLayout(fundoBrancoLayout);
        fundoBrancoLayout.setHorizontalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linhaCc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(VoltarBtn)
                .addGap(18, 18, 18)
                .addComponent(logoDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoBrancoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadSuspBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savCasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadPolBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCasoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        fundoBrancoLayout.setVerticalGroup(
            fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoBrancoLayout.createSequentialGroup()
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fundoBrancoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linhaCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadPolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(fundoBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadSuspBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCasoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(savCasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDeptBtnActionPerformed
        IGCadastrarDepartamento cadastrarDepartamentoPage = new IGCadastrarDepartamento(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            cadastrarDepartamentoPage.setVisible(true);
            this.dispose();
            cadDeptBtn.setVisible(false);    }//GEN-LAST:event_cadDeptBtnActionPerformed

    private void cadSuspBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSuspBtnActionPerformed
        IGCadastrarSuspeito cadastrarSuspeitoPage = new IGCadastrarSuspeito(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            cadastrarSuspeitoPage.setVisible(true);
            this.dispose();
            cadSuspBtn.setVisible(false);    }//GEN-LAST:event_cadSuspBtnActionPerformed

    private void cadTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTestBtnActionPerformed
        IGCadastrarTestemunha cadastrarTestemunhaPage = new IGCadastrarTestemunha(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            cadastrarTestemunhaPage.setVisible(true);
            this.dispose();
            cadTestBtn.setVisible(false);    }//GEN-LAST:event_cadTestBtnActionPerformed

    private void savCasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savCasBtnActionPerformed
            JOptionPane.showMessageDialog(null, "Caso salvo se todos os dados estiverem preenchidos corretamente!");
            IGDelegacia delPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            delPage.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_savCasBtnActionPerformed

    private void cadDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDelBtnActionPerformed
        IGCadastrarDelegacia cadastrarDelegaciaPage = new IGCadastrarDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            cadastrarDelegaciaPage.setVisible(true);
            this.dispose();
            cadDelBtn.setVisible(false);    }//GEN-LAST:event_cadDelBtnActionPerformed

    private void cadPolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPolBtnActionPerformed
        IGCadastrarPolicial cadastrarPolicialPage = new IGCadastrarPolicial(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            cadastrarPolicialPage.setVisible(true);
            this.dispose();
            cadSuspBtn.setVisible(false);    }//GEN-LAST:event_cadPolBtnActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            inicioPage.setVisible(true);
            this.dispose();
            VoltarBtn.setVisible(false);
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void btnInicioLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLinhaActionPerformed
        IGInicio inicioPage = new IGInicio(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        inicioPage.setVisible(true);
        this.dispose();
        btnInicioLinha.setVisible(false);     }//GEN-LAST:event_btnInicioLinhaActionPerformed

    private void btnDelLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLinhaActionPerformed
        IGDelegacia delegaciaPage = new IGDelegacia(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        delegaciaPage.setVisible(true);
        this.dispose();
        btnDelLinha.setVisible(false); 
    }//GEN-LAST:event_btnDelLinhaActionPerformed

    private void btnServicosLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosLinhaActionPerformed
        Servicos servicosPage = new Servicos(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
        servicosPage.setVisible(true);
        this.dispose();
        btnServicosLinha.setVisible(false);
    }//GEN-LAST:event_btnServicosLinhaActionPerformed

    private void cadCasoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCasoBtnActionPerformed
        IGCaso cadastrarCasoPage = new IGCaso(); // Supondo que IGCadastrarDepartamento é uma classe que representa a página de cadastro de departamento.
            cadastrarCasoPage.setVisible(true);
            this.dispose();
            cadCasoBtn.setVisible(false);    }//GEN-LAST:event_cadCasoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JButton btnDelLinha;
    private javax.swing.JButton btnInicioLinha;
    private javax.swing.JButton btnServicosLinha;
    private javax.swing.JButton cadCasoBtn;
    private javax.swing.JButton cadDelBtn;
    private javax.swing.JButton cadDeptBtn;
    private javax.swing.JButton cadPolBtn;
    private javax.swing.JButton cadSuspBtn;
    private javax.swing.JButton cadTestBtn;
    private javax.swing.JPanel fundoBranco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel linhaAe;
    private javax.swing.JPanel linhaCc;
    private javax.swing.JLabel logoDel;
    private javax.swing.JButton savCasBtn;
    private javax.swing.JLabel textoDel;
    private javax.swing.JLabel textoServicos;
    // End of variables declaration//GEN-END:variables
}
